### ISSUE TITLE
Regarding the GPL/BSD license changes

### ISSUE THREAD

**Issue by romatthe** [washingtondc-emu/washingtondc#100]
Hi,

I read your blog post regarding the future of this project on the WashingtonDC home page a few weeks after you posted it. I hope you are doing well.

Since I just noticed today that you started committing this this repo again a while back (and then stopped again around the end of December), I have a few questions regarding the license situation:
1. Does this mean you have some positive news with regards to your health? No need to answer if this is too personal, I just hope you're doing well.
2. Since WashingtonDC is re-licensed as **BSD 3-clause** at b58f004, but has been re-licensed as **GPLv3** again on a468ba7, how would you like us to treat the codebase as a whole? Could we effectively regard the code at b58f004 as being BSD 3-clause licensed, or would you prefer we just treat this repo as if it had been GPLv3-ed on every single commit? I'm not sure on the legal technicalities, I'm more interested in your personal wishes as the author, and I will of course respect those wishes.

I know this perhaps a slightly difficulty question, I'm just asking it because I thought about working with the existing codebase around july (mostly for educational purposes, I'm too dumb to make any productive changes), and I wouldn't want to do anything with your code that would violate the license or your wishes.

**Comment by snickerbockers** [comment]
I relicensed as bsd last summer because i initially intended to abandon the project after i got diagnosed with sarcoma, but eventually i went back to working on it because i realized this protect is very special to me and i don't want to give up on it even if i am dying.

The way the licensing works is that each commit is considered a separate version with its own license which is independent of the other commits. So every commit before b58f004 is GPL, every commit between b58f004 and a468ba7 (not including a468ba7 itself) is BSD, and every commit from a468ba7 onwards is GPL. I'd prefer if people only forked the GPL commits, but if somebody wants the source under BSD license then it's legal for them to fork one of the BSD commits as long as they don't take code from any of the commits after a468ba7.

The current situation with my disease is that i had to get one of my legs amputated, which is why i haven't made any commits in several months; i do intend to return to it eventually, but I'm not sure when. The cancer has also spread to my lungs which means I'll probably be dead in less than five years (only 16% of metastatic sarcoma patients live longer than that).

-------- Original Message --------

**Comment by romatthe** [comment]
Thanks for explaining, that clears things up perfectly!

Sorry to hear about your situation. I wish you all the best in the coming months and years.
